# Домашняя работа

1. Теперь решаем задачу регрессии - предскажем цены на недвижимость. Использовать датасет https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data (train.csv)
2. Построить случайный лес, вывести важность признаков
3. Обучить стекинг как минимум 3х моделей, использовать хотя бы 1 линейную модель и 1 нелинейную
4. В качестве решения: Jupyter notebook с кодом, комментариями и графиками

In [116]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [117]:
data_train = pd.read_csv('train.csv')
data_test = pd.read_csv('test.csv')

data = data_train.append(data_test)

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   object
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   object
 6   Alley          198 non-null    object
 7   LotShape       2919 non-null   object
 8   LandContour    2919 non-null   object
 9   Utilities      2917 non-null   object
 10  LotConfig      2919 non-null   object
 11  LandSlope      2919 non-null   object
 12  Neighborhood   2919 non-null   object
 13  Condition1     2919 non-null   object
 14  Condition2     2919 non-null   object
 15  BldgType       2919 non-null   object
 16  HouseStyle     2919 non-null   object
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   object
 22  RoofMatl       2919 non-null   object
 23  Exterior1st    2918 non-null   object
 24  Exterior2nd    2918 non-null   object
 25  MasVnrType     2895 non-null   object
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   object
 28  ExterCond      2919 non-null   object
 29  Foundation     2919 non-null   object
 30  BsmtQual       2838 non-null   object
 31  BsmtCond       2837 non-null   object
 32  BsmtExposure   2837 non-null   object
 33  BsmtFinType1   2840 non-null   object
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   object
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   object
 40  HeatingQC      2919 non-null   object
 41  CentralAir     2919 non-null   object
 42  Electrical     2918 non-null   object
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   object
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   object
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   object
 58  GarageType     2762 non-null   object
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   object
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   object
 64  GarageCond     2760 non-null   object
 65  PavedDrive     2919 non-null   object
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     object
 73  Fence          571 non-null    object
 74  MiscFeature    105 non-null    object
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   object
 79  SaleCondition  2919 non-null   object
 80  SalePrice      1460 non-null   float64
dtypes: float64(12), int64(26), object(43)
memory usage: 1.8+ MB

In [118]:
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [119]:
data_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [120]:
data_test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [121]:
for col, dtype in data.dtypes.items():
    vc = dict(data[col].value_counts(dropna=False))
    if np.nan in vc:
        print(vc[np.nan], '\t', dtype, col, data[col].unique())

4 	 object MSZoning ['RL' 'RM' 'C (all)' 'FV' 'RH' nan]
2721 	 object Alley [nan 'Grvl' 'Pave']
2 	 object Utilities ['AllPub' 'NoSeWa' nan]
1 	 object Exterior1st ['VinylSd' 'MetalSd' 'Wd Sdng' 'HdBoard' 'BrkFace' 'WdShing' 'CemntBd'
 'Plywood' 'AsbShng' 'Stucco' 'BrkComm' 'AsphShn' 'Stone' 'ImStucc'
 'CBlock' nan]
1 	 object Exterior2nd ['VinylSd' 'MetalSd' 'Wd Shng' 'HdBoard' 'Plywood' 'Wd Sdng' 'CmentBd'
 'BrkFace' 'Stucco' 'AsbShng' 'Brk Cmn' 'ImStucc' 'AsphShn' 'Stone'
 'Other' 'CBlock' nan]
24 	 object MasVnrType ['BrkFace' 'None' 'Stone' 'BrkCmn' nan]
81 	 object BsmtQual ['Gd' 'TA' 'Ex' nan 'Fa']
82 	 object BsmtCond ['TA' 'Gd' nan 'Fa' 'Po']
82 	 object BsmtExposure ['No' 'Gd' 'Mn' 'Av' nan]
79 	 object BsmtFinType1 ['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' nan 'LwQ']
80 	 object BsmtFinType2 ['Unf' 'BLQ' nan 'ALQ' 'Rec' 'LwQ' 'GLQ']
1 	 object Electrical ['SBrkr' 'FuseF' 'FuseA' 'FuseP' 'Mix' nan]
1 	 object KitchenQual ['Gd' 'TA' 'Ex' 'Fa' nan]
2 	 object Functional ['Typ' 'Min1' 'Maj1' 'Min2' 'Mod' 'Maj2' 'Sev' nan]
1420 	 object FireplaceQu [nan 'TA' 'Gd' 'Fa' 'Ex' 'Po']
157 	 object GarageType ['Attchd' 'Detchd' 'BuiltIn' 'CarPort' nan 'Basment' '2Types']
159 	 object GarageFinish ['RFn' 'Unf' 'Fin' nan]
159 	 object GarageQual ['TA' 'Fa' 'Gd' nan 'Ex' 'Po']
159 	 object GarageCond ['TA' 'Fa' nan 'Gd' 'Po' 'Ex']
2909 	 object PoolQC [nan 'Ex' 'Fa' 'Gd']
2348 	 object Fence [nan 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']
2814 	 object MiscFeature [nan 'Shed' 'Gar2' 'Othr' 'TenC']
1 	 object SaleType ['WD' 'New' 'COD' 'ConLD' 'ConLI' 'CWD' 'ConLw' 'Con' 'Oth' nan]

In [122]:
data['MSZoning'] = data['MSZoning'].fillna('NaN')
data['Alley'] = data['Alley'].fillna('No Alley')
data['Utilities'] = data['Utilities'].fillna('No Utilities')
data['MasVnrType'] = data['MasVnrType'].fillna('None')
data['BsmtQual'] = data['BsmtQual'].fillna('No BsmtQual')
data['BsmtCond'] = data['BsmtCond'].fillna('No BsmtQual')
data['BsmtExposure'] = data['BsmtExposure'].fillna('No BsmtExposure')
data['BsmtFinType1'] = data['BsmtFinType1'].fillna('No BsmtFinType1')
data['BsmtFinType2'] = data['BsmtFinType2'].fillna('No BsmtFinType2')
data['FireplaceQu'] = data['FireplaceQu'].fillna('No FireplaceQu')
data['MiscFeature'] = data['MiscFeature'].fillna('No MiscFeature')
data['GarageType'] = data['GarageType'].fillna('No GarageType')
data['GarageFinish'] = data['GarageFinish'].fillna('No GarageFinish')
data['GarageQual'] = data['GarageQual'].fillna('No GarageQual')
data['GarageCond'] = data['GarageCond'].fillna('No GarageCond')
data['PoolQC'] = data['PoolQC'].fillna('No PoolQC')
data['Fence'] = data['Fence'].fillna('No FenceMiscFeature')

data['SalePrice'] = data['SalePrice'].fillna(0)

data = data.dropna()

data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,No Alley,Reg,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,No Alley,Reg,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,No Alley,IR1,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,No Alley,IR1,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,No Alley,IR1,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1451,2912,20,RL,80.0,13384,Pave,No Alley,Reg,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,5,2006,WD,Normal,0.0
1452,2913,160,RM,21.0,1533,Pave,No Alley,Reg,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,12,2006,WD,Abnorml,0.0
1455,2916,160,RM,21.0,1894,Pave,No Alley,Reg,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,4,2006,WD,Abnorml,0.0
1456,2917,20,RL,160.0,20000,Pave,No Alley,Reg,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,9,2006,WD,Abnorml,0.0
1458,2919,60,RL,74.0,9627,Pave,No Alley,Reg,Lvl,AllPub,...,0,No PoolQC,No FenceMiscFeature,No MiscFeature,0,11,2006,WD,Normal,0.0

In [128]:
data_train = data[data['SalePrice'] > 0]
data_test = data[data['SalePrice'] == 0]

data_train.shape, data_test.shape

((1120, 81), (1142, 81))

nan_cols = ['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature']

data_train = data_train.drop(nan_cols, axis=1).dropna()
data_test = data_test.drop(nan_cols, axis=1).dropna()

In [129]:
from sklearn.preprocessing import LabelEncoder

def get_labeled_df(df, skipna=True):
    res = df.copy()
    for col, dtype in res.dtypes.items():
        if dtype == np.object:
            le = LabelEncoder()
            if skipna:
                ### fit with the desired col, col in position 0 for this example
                fit_by = pd.Series([i for i in res[col].unique() if type(i) == str])
                le.fit(fit_by)
                ### Set transformed col leaving np.NaN as they are
                res[col] = res[col].apply(lambda x: le.transform([x])[0] if type(x) == str else x)
            else:
                res[col][pd.isnull(res[col])]  = 'NaN'
                res[col] = le.fit_transform(res[col])
    return res

In [130]:
lbl_train = get_labeled_df(data_train, False).dropna()
lbl_test = get_labeled_df(data_test, False).dropna()

<ipython-input-129-e2f0e2e0f072>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res[col][pd.isnull(res[col])]  = 'NaN'
<ipython-input-129-e2f0e2e0f072>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res[col][pd.isnull(res[col])]  = 'NaN'

In [131]:
X_train = lbl_train.drop('SalePrice', axis=1)
y_train = lbl_train['SalePrice']
X_test = lbl_test

In [132]:
X_train.shape, y_train.shape

((1120, 80), (1120,))

In [133]:
lbl_test.shape

(1142, 81)

In [134]:
from sklearn.ensemble import RandomForestClassifier

clf_rf = RandomForestClassifier(n_estimators=10, max_depth=5, min_samples_leaf=20, max_features=0.5, n_jobs=-1)
clf_rf.fit(X_train, y_train)
clf_rf.score(X_train, y_train)

0.14017857142857143

In [135]:
y_pred = clf_rf.predict(X_train)

tmp = lbl_train.copy()
tmp['pred'] = y_pred
tmp['sqr_diff'] = (tmp['pred'] - tmp['SalePrice']) ** 2

tmp

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,pred,sqr_diff
0,1,60,3,65.0,8450,1,1,3,3,0,...,4,0,0,2,2008,8,4,208500.0,190000.0,3.422500e+08
1,2,20,3,80.0,9600,1,1,3,3,0,...,4,0,0,5,2007,8,4,181500.0,145000.0,1.332250e+09
2,3,60,3,68.0,11250,1,1,0,3,0,...,4,0,0,9,2008,8,4,223500.0,230000.0,4.225000e+07
3,4,70,3,60.0,9550,1,1,0,3,0,...,4,0,0,2,2006,8,0,140000.0,140000.0,0.000000e+00
4,5,60,3,84.0,14260,1,1,0,3,0,...,4,0,0,12,2008,8,4,250000.0,250000.0,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,1,3,3,0,...,4,0,0,8,2007,8,4,175000.0,181000.0,3.600000e+07
1456,1457,20,3,85.0,13175,1,1,3,3,0,...,2,0,0,2,2010,8,4,210000.0,175000.0,1.225000e+09
1457,1458,70,3,66.0,9042,1,1,3,3,0,...,0,2,2500,5,2010,8,4,266500.0,180000.0,7.482250e+09
1458,1459,20,3,68.0,9717,1,1,3,3,0,...,4,0,0,4,2010,8,4,142125.0,130000.0,1.470156e+08
1459,1460,20,3,75.0,9937,1,1,3,3,0,...,4,0,0,6,2008,8,4,147500.0,145000.0,6.250000e+06

In [136]:
(tmp['sqr_diff'].sum() / len(tmp)) ** (1 / 2)

54410.13259731264